apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::650251696513:role/flaskanetes-dev-aws-load-balancer-controller"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  repo: https://aws.github.io/eks-charts
  chart: aws-load-balancer-controller
  version: 1.7.1
  targetNamespace: kube-system
  valuesContent: |-
    clusterName: flaskanetes-dev
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
    region: ap-southeast-2
    vpcId: ${module.vpc.vpc_id} 