apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskanetes
  labels:
    app: flaskanetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskanetes
  template:
    metadata:
      labels:
        app: flaskanetes
    spec:
      containers:
      - name: flaskanetes
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/flaskanetes:latest  # This will be updated by the CD workflow
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi" 