name: CD

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  EKS_CLUSTER: flaskanetes-cluster
  AWS_REGION: us-west-2  # Change this to your desired region

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
      
    - name: Deploy to EKS
      run: |
        # Update the image tag in the deployment
        kubectl set image deployment/flaskanetes \
          flaskanetes=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -n flaskanetes
        
        # Wait for rollout to complete
        kubectl rollout status deployment/flaskanetes -n flaskanetes 