name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/flaskanetes-github-actions-${{ github.event.inputs.environment }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: terraform/environments/${{ github.event.inputs.environment }} 